Allen added a Dockerfile and a Jenkinsfile
thisisrishabh22/lazy-learning pull request #2
Opened 2023-12-17 20:49 UTC by allengb208

Hello Rishabh,

I am Allen . I came across your profile on Quine and was impressed by the application you submitted for the SWOC. I took the liberty of enhancing it by adding a Dockerfile and a Jenkinsfile. I believe these additions will further improve the functionality of your app. I encourage you to take a look when you have a moment.

2023-12-18 05:26 UTC, thisisrishabh22 commented on Dockerfile
Hi @allengb208 
I think the following Docker file has development environment setup. I generally prefer using production environment setup for deployments and that's the recommended practice as well. 

Is it possible for you to refactor it and migrate it to production environment.

Also I would appreciate if you could also add `docker compose` file as well.

2023-12-18 05:27 UTC, thisisrishabh22 requested changes
@allengb208 

I would appreciate if you can update the `Dockerfile` and add a `docker compose` file as well.

2023-12-21 06:38 UTC, allengb208 commented on Dockerfile
Hi Rishabh , Ya sure if you wan't i can add some Kubernetes manifests too.

2023-12-22 18:20 UTC, thisisrishabh22 approved these changes
LGTM, Merging!

2023-12-22 18:22 UTC, thisisrishabh22 commented on Dockerfile
Hi @allengb208 

Thanks for collaborating I'll be merging the changes, might add some of my own additions as well

2023-12-22 18:28 UTC, merged